// secrets_example.h
#pragma once

// WiFi
#define WIFI_SSID1 "YOUR_WIFI_SSID"
#define WIFI_PASS1 "YOUR_WIFI_PASSWORD"
#define WIFI_SSID2 "OPTIONAL_SECOND_SSID"
#define WIFI_PASS2 "OPTIONAL_SECOND_PASSWORD"

// API Keys
#define TOKEN_METEOCONSULT "YOUR_METEOCONSULT_TOKEN"
#define TOKEN_OPENWEATHER "YOUR_OPENWEATHER_TOKEN"
#define TOKEN_WEATHERBIT "YOUR_WEATHERBIT_TOKEN"
#define TOKEN_WEATHERBIT_ALT "YOUR_WEATHERBIT_ALT_TOKEN"
#define TOKEN_ACCUWEATHER "YOUR_ACCUWEATHER_TOKEN"
#define ACCU_LOCATION_KEY "YOUR_LOCATION_KEY"

// u-blox AssistNow
#define TOKEN_UBLOX_AGPS "YOUR_UBLOX_TOKEN"

// Telegram
#define TELEGRAM_BOT_TOKEN "YOUR_TELEGRAM_BOT_TOKEN"
#define TELEGRAM_CHAT_ID "YOUR_TELEGRAM_CHAT_ID"
